# Web Scraping

In [1]:
# import Libraries
import numpy as np
import pandas as pd
import re
import requests
from bs4 import BeautifulSoup

import time

from IPython.core.interactiveshell import InteractiveShell

In [2]:
URL='https://www.value.today/world/world-top-500-companies'

In [3]:
website=requests.get(URL)

In [4]:
website.status_code  # A status code 200 means we are allowed to scrape the data

200

In [6]:
websitecontent=website.text

In [7]:
websoup=BeautifulSoup(websitecontent)

In [14]:
com_names=[]
worldranks=[]
market_cap=[]
headq_of_companies=[]
sectors=[]
annual_rev=[]
annual_net_inc=[]
tot_assets=[]
total_emp=[]
employ_count=[]
ceos=[]

for x in websoup.find_all('div',attrs={'class':'row well views-row'}):
    com_name=x.find('div',attrs={'class':'views-field views-field-title col-sm-12 clearfix'})
    if com_name is None:
        com_names.append(np.NaN)
    else:
        com_names.append(com_name.text)

    
    worldrank=x.find('div',attrs={'class':'views-field views-field-field-world-rank-jan-2020 clearfix col-sm-12'})
    if worldrank is None:
        worldranks.append(np.NaN)
    else:
        worldranks.append(worldrank.text)
    
    mar_cap=x.find('div',attrs={'class':'views-field views-field-field-market-value-jan-2020 clearfix col-sm-12'})
    if mar_cap is None:
        market_cap.append(np.NaN)
    else:
        market_cap.append(mar_cap.text)
    
    headq_of_com=x.find('div',attrs={'class':'views-field views-field-field-headquarters-of-company clearfix col-sm-12'})
    if headq_of_com is None:
        headq_of_companies.append(np.NaN)
    else:
        headq_of_companies.append(headq_of_com.text)
    
    sector=x.find('div',attrs={'class':'views-field views-field-field-company-category-primary clearfix col-sm-12'})
    if sector is None:
        sectors.append(np.NaN)
    else:
        sectors.append(sector.text)
    
    ann_rev=x.find('div',attrs={'class':'views-field views-field-field-annual-revenue clearfix col-sm-12'})
    if ann_rev is None:
        annual_rev.append(np.NaN)
    else:
        annual_rev.append(ann_rev.text)
    
    ann_net_inc=x.find('div',attrs={'class':'views-field views-field-field-annual-net-income-lc clearfix col-sm-12'})
    if ann_net_inc is None:
        annual_net_inc.append(np.NaN)
    else:
        annual_net_inc.append(ann_net_inc.text)
    
    tot_ass=x.find('div',attrs={'class':'views-field views-field-field-total-assets clearfix col-sm-12'})
    if tot_ass is None:
        tot_assets.append(np.NaN)
    else:
        tot_assets.append(tot_ass.text)
    
    tot_emp=x.find('div',attrs={'class':'views-field views-field-field-employee-count clearfix col-sm-12'})
    if tot_emp is None:
        total_emp.append(np.NaN)
    else:
        total_emp.append(tot_emp.text)
    
    emp_count=x.find('div',attrs={'class':'views-field views-field-field-employee-count-as-on-date clearfix col-sm-12'})
    if emp_count is None:
        employ_count.append(np.NaN)
    else:
        employ_count.append(emp_count.text)
    
    ceo=x.find('div',attrs={'class':'views-field views-field-field-ceo clearfix col-sm-12'})
    if ceo is None:
        ceos.append(np.NaN)
    else:
        ceos.append(ceo.text)

In [15]:
company_df=pd.DataFrame({'Company_Names':com_names,'World_Ranks':worldranks,
                         'Market_Cap':market_cap,'Headquarter_of_Company':headq_of_companies,
                         'Sector':sectors,'Annual_Rev':annual_rev,'Annual_Net_Inc':annual_net_inc,
                         'Total_Assets':tot_assets,'Total_Employees':total_emp,'Employee_Count_as_on_Date':employ_count,'CEO':ceos})

In [16]:
company_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Company_Names              500 non-null    object
 1   World_Ranks                500 non-null    object
 2   Market_Cap                 474 non-null    object
 3   Headquarter_of_Company     500 non-null    object
 4   Sector                     500 non-null    object
 5   Annual_Rev                 497 non-null    object
 6   Annual_Net_Inc             481 non-null    object
 7   Total_Assets               254 non-null    object
 8   Total_Employees            498 non-null    object
 9   Employee_Count_as_on_Date  494 non-null    object
 10  CEO                        466 non-null    object
dtypes: object(11)
memory usage: 43.1+ KB

In [17]:
company_df

,Company_Names,World_Ranks,Market_Cap,Headquarter_of_Company,Sector,Annual_Rev,Annual_Net_Inc,Total_Assets,Total_Employees,Employee_Count_as_on_Date,CEO
0,SAUDI ARABIAN OIL COMPANY (Saudi Aramco),World Rank (Jan-2020): 1,Market Cap (Jan-01-2020): 1898.10 Billion USD,Headquarters of Company: Saudi Arabia,"Sector: Energy, Oil and Gas, Chemicals, Oil Re...",Annual Revenue: Saudi Aramco Annual Revenues f...,Annual Net Income: Saudi Aramco Annual Net Inc...,Total Assets: Total Assets of Saudi Aramco as ...,"Total Employees: 79,800",Employee Count as on Date: As on March 2021,CEO: Amin H. Al-Nasser
1,APPLE,World Rank (Jan-2020): 2,Market Cap (Jan-01-2020): 1323.00 Billion USD,Headquarters of Company: USA,"Sector: Technology, Mobiles & Accessories, Ele...",Annual Revenue: Apple Annual Revenues for Sept...,Annual Net Income: Apple Annual Net Income for...,Total Assets: Apple Total Assets as on June-27...,"Total Employees: 154,000",Employee Count as on Date: As on 2021,CEO: Tim Cook
2,MICROSOFT CORPORATION,World Rank (Jan-2020): 3,Market Cap (Jan-01-2020): 1215.00 Billion USD,Headquarters of Company: USA,"Sector: Technology, Software and IT, Laptops, ...",Annual Revenue: Microsoft Annual Revenues for ...,Annual Net Income: Microsoft Annual Net Income...,Total Assets: Total Assets of Microsoft Corpor...,"Total Employees: 182,268",Employee Count as on Date: As on Dec-2021,CEO: Satya Nadella
3,ALPHABET,World Rank (Jan-2020): 4,Market Cap (Jan-01-2020): 943.90 Billion USD,Headquarters of Company: USA,"Sector: Technology, Internet or Mobile App Bas...",Annual Revenue: Alphabet Annual Revenues for D...,Annual Net Income: Alphabet Annual Net Income ...,Total Assets: 299.243 Billion USD as on Sep-2020,"Total Employees: 156,500",Employee Count as on Date: As on Dec-2021,CEO: Sundar Pichai
4,AMAZON.COM,World Rank (Jan-2020): 5,Market Cap (Jan-01-2020): 941.03 Billion USD,Headquarters of Company: USA,"Sector: eCommerce, Internet or Mobile App Base...",Annual Revenue: Amazon Annual Revenues for Dec...,Annual Net Income: Amazon Annual Net Income fo...,Total Assets: Total Assets of Amazon as on Jun...,"Total Employees: 1,335,000",Employee Count as on Date: As on 2021,CEO: Andy Jassy
...,...,...,...,...,...,...,...,...,...,...,...
495,SEVEN & I HOLDINGS,World Rank (Jan-2020): 471,Market Cap (Jan-01-2020): 32.65 Billion USD,Headquarters of Company: Japan,"Sector: Consumer Defensive, Retail, Super Mark...",Annual Revenue: SEVEN & I HOLDINGS Annual Reve...,Annual Net Income: SEVEN & I HOLDINGS Annual N...,NaN,"Total Employees: 138,808",Employee Count as on Date: As on 2021,CEO: Ryuichi Isaka
496,ASSICURAZIONI GENERALI,World Rank (Jan-2020): 472,Market Cap (Jan-01-2020): 32.61 Billion USD,Headquarters of Company: Italy,"Sector: Financial Services, Insurance",Annual Revenue: ASSICURAZIONI GENERALI Annual ...,Annual Net Income: ASSICURAZIONI GENERALI Annu...,NaN,"Total Employees: 72,644",Employee Count as on Date: As on May 2021,CEO: Philippe Donnet
497,AMPHENOL CORPORATION,World Rank (Jan-2020): 473,Market Cap (Jan-01-2020): 32.53 Billion USD,Headquarters of Company: USA,"Sector: Technology, Electronics, Cables and Wi...",Annual Revenue: AMPHENOL CORPORATION Annual Re...,Annual Net Income: AMPHENOL CORPORATION Annual...,NaN,"Total Employees: 90,000",Employee Count as on Date: As on 2021,CEO: Richard Adam Norwitt
498,GENERAL MILLS,World Rank (Jan-2020): 474,Market Cap (Jan-01-2020): 32.52 Billion USD,Headquarters of Company: USA,"Sector: Consumer Defensive, Food Products, FMC...",Annual Revenue: GENERAL MILLS Annual Revenues ...,Annual Net Income: GENERAL MILLS Annual Net In...,Total Assets: GENERAL MILLS Total Assets as on...,"Total Employees: 35,000",Employee Count as on Date: As on 2021,CEO: Jeff Harmening
499,FOMENTO ECONOMICO MEXICANOB. DE C.V. (FEMSA),World Rank (Jan-2020): 475,Market Cap (Jan-01-2020): 32.46 Billion USD,Headquarters of Company: Mexico,"Sector: Consumer Defensive, Non-Alcoholic Beve...",Annual Revenue: FEMSA Annual Revenues as on De...,Annual Net Income: FEMSA Annual Net Income as ...,NaN,"Total Employees: 320,618",Employee Count as on Date: As on 2020,CEO: Eduardo Padilla Silva

In [18]:
company_df.to_csv(r'C:\projects\Company_20220625.csv')

In [20]:
company_df.to_excel(r'C:\projects\Company_20220625.xlsx')

In [21]:
company_df.head()

,Company_Names,World_Ranks,Market_Cap,Headquarter_of_Company,Sector,Annual_Rev,Annual_Net_Inc,Total_Assets,Total_Employees,Employee_Count_as_on_Date,CEO
0,SAUDI ARABIAN OIL COMPANY (Saudi Aramco),World Rank (Jan-2020): 1,Market Cap (Jan-01-2020): 1898.10 Billion USD,Headquarters of Company: Saudi Arabia,"Sector: Energy, Oil and Gas, Chemicals, Oil Re...",Annual Revenue: Saudi Aramco Annual Revenues f...,Annual Net Income: Saudi Aramco Annual Net Inc...,Total Assets: Total Assets of Saudi Aramco as ...,"Total Employees: 79,800",Employee Count as on Date: As on March 2021,CEO: Amin H. Al-Nasser
1,APPLE,World Rank (Jan-2020): 2,Market Cap (Jan-01-2020): 1323.00 Billion USD,Headquarters of Company: USA,"Sector: Technology, Mobiles & Accessories, Ele...",Annual Revenue: Apple Annual Revenues for Sept...,Annual Net Income: Apple Annual Net Income for...,Total Assets: Apple Total Assets as on June-27...,"Total Employees: 154,000",Employee Count as on Date: As on 2021,CEO: Tim Cook
2,MICROSOFT CORPORATION,World Rank (Jan-2020): 3,Market Cap (Jan-01-2020): 1215.00 Billion USD,Headquarters of Company: USA,"Sector: Technology, Software and IT, Laptops, ...",Annual Revenue: Microsoft Annual Revenues for ...,Annual Net Income: Microsoft Annual Net Income...,Total Assets: Total Assets of Microsoft Corpor...,"Total Employees: 182,268",Employee Count as on Date: As on Dec-2021,CEO: Satya Nadella
3,ALPHABET,World Rank (Jan-2020): 4,Market Cap (Jan-01-2020): 943.90 Billion USD,Headquarters of Company: USA,"Sector: Technology, Internet or Mobile App Bas...",Annual Revenue: Alphabet Annual Revenues for D...,Annual Net Income: Alphabet Annual Net Income ...,Total Assets: 299.243 Billion USD as on Sep-2020,"Total Employees: 156,500",Employee Count as on Date: As on Dec-2021,CEO: Sundar Pichai
4,AMAZON.COM,World Rank (Jan-2020): 5,Market Cap (Jan-01-2020): 941.03 Billion USD,Headquarters of Company: USA,"Sector: eCommerce, Internet or Mobile App Base...",Annual Revenue: Amazon Annual Revenues for Dec...,Annual Net Income: Amazon Annual Net Income fo...,Total Assets: Total Assets of Amazon as on Jun...,"Total Employees: 1,335,000",Employee Count as on Date: As on 2021,CEO: Andy Jassy